# basic configuration data  ...................................
max_rec_count: 99999
sub_directory: data/
visit_timeout: 1200
#log_level options are debug, info, warn, error, fatal
log_level: info
log_record_counts: true
convert_to_lower_case: true
url_stem: /
accept_only_url_stem: false
include_urls:
- .htm
- .pdf
- home.aspx
exclude_urls:
- .html
# sitemap_match: true
hostname: www.sigma-systems.com
drop_refers_by_hostname: false 
# output_where_rank_over: 2
use_local_time: true
drop_ips:
- 10.131.0.4
- 76.12.171.4
- 76.12.185.100
spider_ips:
- 66.98.254.55
# post processing instructions ..............................
output_where_rank_over: 2
sitemap_match: true
# spider and user agents ....................................
spider_names:
- bot
- spider
- slurp
- root.exe
- looksmart
- nutchsvc
- iconsurf
- objectsearch
- openfind
- iltovatore
- mozdex
- netresearch
- konsqueror
- crawler	
- searchme
- findlinks
- scoutjet
- yeti
- yandex
- fetch
- nutch
- sleuth
- globalspec
- openurl
- python
- acoon
- itim
- metauri
- extractor
- exractor
- pagegetter
- linkdex
- website
- xfruits
- binlar
- abacus
- anemone
- ichiro
- scraping
- xpymep
- swish
- sitemaps
- yahoocachesystem
- sexy
- .dll
- java/1
usual_agents:
- mozilla
- opera
- chrome
- lynx
- nokia
- blackberry
- sharp
- docomo
- curl
- facebook
- microsoft
- securepoint
- wordpress
# advanced: db lookups and csv ..................................
whois_lookup: true
use_db_lookup: true
use_db_visits: true
# create_csv_file: false
# advanced: email notification ..................................
admin_email: ...
user_email: ..
email_server: ...
send_logmsg_admin: ...
# advanced: google docs connection ..............................
use_gdocs: ...
gdocs_user: ...
gdocs_password: ...
gdocs_key: ...
